# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Mkdocs Material YML configuration example
theme:
  name: material

plugins:
  - projects:
      projects_dir: languages
