# Se lit mieux sur VSCode avec le module TODO Highlight v2

### informations générales

# TODO: Nom affiché dans le menu du haut et dans les onglets du navigateur
site_name: Exemple de configuration YMl de Mkdocs Material 
# TODO: URL du site web (important pour la bonne construction du site!)
site_url: https://flaghunter01.github.io/mkdocs-yml/fr/
# TODO: URL de la repo GitHub
repo_url: https://github.com/FlagHunter01/mkdocs-yml/
# TODO: Nom de la repo GitHub
repo_name: mkdocs-yml 

### Navigation

nav: 
  - Acceuil: index.md
  - Blog: blog/index.html
  - Guide: 
    - guide/index.md
    - Installation: guide/setup.md
    - Utilisation: guide/useage.md

### Personnalisation du thème

theme:
  # Utilisation du thème Material
  name: material

  ## Couleurs

  palette:
    # Mode automatique de la palette des couleurs
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: deep purple
      accent: light blue
    # Mode clair de la palette
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: light blue
    #Mode sombre de la palette
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: teal
      accent: amber

  ## Police

  # Si le module privacy n'est pas utilisé, décommenter la ligne suivante pour rester dans le RGPD
  #font: false
  font:
    # Tout le texte sauf le code
    text: Roboto
    # Code en blocs et en ligne
    code: Roboto Mono
  
  ## Langue

  # TODO: Ne pas oublier de la changer s'il s'agit d'un projet multilingue
  language: fr

  ## Logo et icones

  # TODO: Utilisation d'une image personnalisée
  #logo: assets/logo.png
  # TODO: Utilisation d'une icone fournie
  #icon:
  #  logo: material/library
  # TODO: favicon (icone dans l'onglet du navigateur)
  #favicon: assets/favicon.png

  features:
    
    ## Navigation

    # Mode monopage utilisant le XHR
    - navigation.instant
    # Pré-téléchargement des pages lorsque l'utilisateur survole un lien (diminution du temps de téléchargement percu)
    - navigation.instant.prefetch
    # Afficher la barre de chargement(ne s'affiche que si le chargement dure plsu de 0.4s) 
    - navigation.instant.progress
    # Prévisualisation des liens
    - navigation.instant.preview
    # Tracage de l'ancre (anchor)
    - navigation.tracking
    # Afficher les sections dans le menu du haut
    - navigation.tabs
    # Affichage du chemin de la page en haut
    - navigation.path
    # Autoriser les sections d'avoir leur propre index
    - navigation.indexes
    # Bouton "Retour en haut de page"
    - navigation.top
    # Navigation en pied-de-page
    - navigation.footer

    ## Recherche

    # Suggestions de recherche
    - search.suggest
    # Surligner les résultats de la recherche
    - search.highlight

    ## Intégration GitHub
    
    # Bouton pour visualiser le code source de la page
    - content.action.view

    ## Blocs de code

    # Bouton de copie
    - content.code.copy
    # Bouton pour sélectionner des lignes discretes
    - content.code.select
    # Annotations
    - content.code.annotate

    ## Misc

    # Joindre les tableaux de contenu ensemble
    - content.tabs.link
    # Afficher les notes de pied-de-page comme des tooltips
    - content.footnote.tooltips
    # Tooltips
    - content.tooltips

### Plugins

plugins:
  # Vie privée (RGPD)
  - privacy
  # Recherche
  - search
  # Cartes de visite (Twitter, Discord etc)
  - social
  # Blog
  - blog
  # RSS
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
  # Dates Git
  - git-revision-date-localized:
      # Afficher la date de création en plus de la date de dernière modification
      enable_creation_date: true
  # FIXME:Git commiters 
  #- git-committers:
    # TODO: Repo URL
  #    repository: FlagHunter01/school
    # TODO: Branch
  #    branch: main
  # Mode hors-ligne
  - offline

    
extra:
  ### Réseaux

  # TODO: modifier
  social:
    - icon: material/github
      link: https://github.com/FlagHunter01

  ### Sélection de langue

  alternate:
    - name: English
      link: ../en/
      lang: en
    - name: Français
      link: .
      lang: fr

markdown_extensions:
  # Abbreviations: RER *[RER]: Réseau Express Régional  --> <p><abbr title="Réseau Express Régional">RER</abbr></p>
  - abbr
  # Avertissements
  - admonition
  # Avertissements pliables
  - pymdownx.details
  # Annotations 
  - md_in_html
  # Notes sur la même ligne
  - footnotes
  # Table des matières
  - toc:
    # Rendre l'ancre visible
      permalink: ⚓︎
  # Tableaux
  - tables
  # Détection intelligente du gras et de l'italique
  - pymdownx.betterem
  # Surligner le texte
  - pymdownx.caret
  # Surligner le code
  - pymdownx.highlight:
      anchor_linenums: true
  # Surligner le code en ligne
  - pymdownx.inlinehilite
  # imbrication du code et des avertissements
  - pymdownx.superfences
  # Indice 
  - pymdownx.mark
  # Exposant 
  - pymdownx.tilde
  # Support du diff
  - pymdownx.critic
  # Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Dessiner les touches de clavier
  - pymdownx.keys
  # Transformer les stings spéciaux en symboles, par ex.: &copy --> ©
  - pymdownx.smartsymbols
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Listes de taches
  - pymdownx.tasklist:
      custom_checkbox: true
    # Les rendre cochables
      clickable_checkbox: true
  # Boutons
  - attr_list
